# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - web3ads-api

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/main_web3ads-api.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build
        working-directory: ./server
        run: |
          npm install
          npm run build
          rm -rf node_modules
          npm install --omit=dev --ignore-scripts
          npx prisma generate
          
      - name: Create deployment package
        working-directory: ./server
        run: |
          mkdir -p deploy
          cp -r dist deploy/
          cp -r node_modules deploy/
          cp package.json deploy/
          cp -r prisma deploy/

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "web3ads-api"
          slot-name: "Production"
          package: ./server/deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_053A9E9440094A7D8509F803FD9373D7 }}
